[2023-05-05T06:00:20.923+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chatgpt_dag.delete_file scheduled__2023-05-05T05:55:00+00:00 [queued]>
[2023-05-05T06:00:20.928+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chatgpt_dag.delete_file scheduled__2023-05-05T05:55:00+00:00 [queued]>
[2023-05-05T06:00:20.928+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-05T06:00:20.928+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-05T06:00:20.928+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-05T06:00:20.939+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): delete_file> on 2023-05-05 05:55:00+00:00
[2023-05-05T06:00:20.942+0000] {standard_task_runner.py:55} INFO - Started process 377327 to run task
[2023-05-05T06:00:20.944+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'chatgpt_dag', 'delete_file', 'scheduled__2023-05-05T05:55:00+00:00', '--job-id', '4481', '--raw', '--subdir', 'DAGS_FOLDER/chatgpt_dag.py', '--cfg-path', '/tmp/tmp15k3jvmr']
[2023-05-05T06:00:20.944+0000] {standard_task_runner.py:83} INFO - Job 4481: Subtask delete_file
[2023-05-05T06:00:20.973+0000] {task_command.py:389} INFO - Running <TaskInstance: chatgpt_dag.delete_file scheduled__2023-05-05T05:55:00+00:00 [running]> on host trivia-machine.us-central1-a.c.triviapractice-381517.internal
[2023-05-05T06:00:21.018+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=richc
AIRFLOW_CTX_DAG_ID=chatgpt_dag
AIRFLOW_CTX_TASK_ID=delete_file
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T05:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-05T05:55:00+00:00
[2023-05-05T06:00:21.022+0000] {logging_mixin.py:137} INFO - /home/rich2/airflow/scripts/chatgpt_output/ushistory_2023-05-05_06-00-13.json deleted successfully
[2023-05-05T06:00:21.022+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-05T06:00:21.024+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=chatgpt_dag, task_id=delete_file, execution_date=20230505T055500, start_date=20230505T060020, end_date=20230505T060021
[2023-05-05T06:00:21.075+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-05T06:00:21.083+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
