[2023-05-04T08:55:18.539+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chatgpt_dag.delete_file scheduled__2023-05-04T08:50:00+00:00 [queued]>
[2023-05-04T08:55:18.543+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chatgpt_dag.delete_file scheduled__2023-05-04T08:50:00+00:00 [queued]>
[2023-05-04T08:55:18.543+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T08:55:18.543+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-04T08:55:18.544+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T08:55:18.553+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): delete_file> on 2023-05-04 08:50:00+00:00
[2023-05-04T08:55:18.556+0000] {standard_task_runner.py:55} INFO - Started process 284468 to run task
[2023-05-04T08:55:18.558+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'chatgpt_dag', 'delete_file', 'scheduled__2023-05-04T08:50:00+00:00', '--job-id', '3409', '--raw', '--subdir', 'DAGS_FOLDER/chatgpt_dag.py', '--cfg-path', '/tmp/tmp22ar_dea']
[2023-05-04T08:55:18.558+0000] {standard_task_runner.py:83} INFO - Job 3409: Subtask delete_file
[2023-05-04T08:55:18.588+0000] {task_command.py:389} INFO - Running <TaskInstance: chatgpt_dag.delete_file scheduled__2023-05-04T08:50:00+00:00 [running]> on host trivia-machine.us-central1-a.c.triviapractice-381517.internal
[2023-05-04T08:55:18.630+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=richc
AIRFLOW_CTX_DAG_ID=chatgpt_dag
AIRFLOW_CTX_TASK_ID=delete_file
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T08:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-04T08:50:00+00:00
[2023-05-04T08:55:18.634+0000] {logging_mixin.py:137} INFO - /home/rich2/airflow/scripts/chatgpt_output/oscars_2023-05-04_08-55-14.json deleted successfully
[2023-05-04T08:55:18.635+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-04T08:55:18.637+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=chatgpt_dag, task_id=delete_file, execution_date=20230504T085000, start_date=20230504T085518, end_date=20230504T085518
[2023-05-04T08:55:18.649+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-04T08:55:18.656+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
